### ISSUE TITLE
Issue installing Rdkit properly

### ISSUE THREAD

**Issue by pythonnewbie3** [greglandrum/rdkit_blog#3]
I've tried to install rdkit 5times using anaconda, but I don't get the new 2020 version. 

Also I can't access it trough Spyder, Idle, or Pycharm eventhough I installed it. Is there something I can do? 

Thanks in advance

**Comment by greglandrum** [comment]
Without more information about which system you're on, which version of python and conda you are using, and exactly which commands you ran, I can't help.
I would suggest starting a new conda environment and installing the rdkit in that environment along with whatever additional packages you need. This should get you the most recent version.

**Comment by pythonnewbie3** [comment]
Hi,
thank you for your reply. I'm using Windows 10 with Python 3.9.1. 64 bit- I installed Anaconda3 32 bit 2 days ago, but then I relized I need the 64 bit version to be compatible with my python. Then I deinstalled Anaconda and reinstalled the 64 bit version.

After that I ran the following comands in the conda terminal:
conda create -c rdkit -n my-rdkit-env rdkit
conda activate my-rdkit-env

After that I tried to use rdkit in Idle, but I got the Error message that there is no modul named like that. After that I moved the rdkit files from the corresponding envioment to the path Idle is using. Now I get the following error:
from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'

I then proceeded to reinstall it in the environment, and try to use it with spyder or pycharm, but both of them can't find the module. Also Anaconda is not installing or updating the version from 2020, it just installs the 2017 version of rdkit.

**Comment by greglandrum** [comment]
I assume that you havent' properly configured idle, spyder, or pycharm to use the environment you created.
I don't use these tools, so I don't know how to do that, but I suspect that if you do a web search for rdkit and idle or rdkit and pycharm you will find some answers.

As an aside: I recommend that you install the rdkit from the conda-forge channel instead of the rdkit channel.
The conda-forge versions are automatically built and more up to date.

**Comment by pythonnewbie3** [comment]
Thank you, do I have to deinstall the version from the rdkit channel?

**Comment by greglandrum** [comment]
that's probably a good idea

**Comment by pythonnewbie3** [comment]
What's the correct command for deinstallation?

conda deactivate my-rdkit-env

**Comment by greglandrum** [comment]
there is plenty of great documentation online for how to use conda

**Comment by pythonnewbie3** [comment]
thank you, I managed to install it properly now. But i can't use the drawing function in spyder? No molecules appear

**Comment by greglandrum** [comment]
as I said before, I don't use these IDEs, so I can't help you here.

**Comment by JohnMommers** [comment]
I suddenly have an issue installing Rdkit on Google Colab (this was not an issue before) using the following: 

I!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e

I get an error when:
from rdkit import Chem

Again m y Colab scipts worked before and now I get this error. What should I do. Thanks.

**Comment by pythonnewbie3** [comment]
@greglandrum 

Is it possible to change the following command to count other elements than hydrogen:


mol = Chem.MolFromSmiles("C(OC(CCCCCCC(OCCSC(CCCCCC1)=O)=O)OCCSC1=O)N1CCOCC1")
mol = Chem.AddHs(mol)


I  tried mol= Chem.AddCs for the carbons but it did not work. 

I want to extract the numbers of Carbons, Oxygens, Nitrogens, Fluorines, Bromines, Iodines and Chlorines.

**Comment by greglandrum** [comment]
This is not the place to ask RDKit questions. Please use the RDKit mailing list or the discussion tab in the main RDKit repo for that.
