### ISSUE TITLE
ETKDG Modul

### ISSUE THREAD

**Issue by pythonnewbie3** [greglandrum/rdkit_blog#4]
Dear Mr. Landrum,

im currently trying to program a molecule generator using the ETKGD module. Unfortunately, I can't find out how to convert the output of it to a list of SMILES. Is this possible, or is there another way to get a list of SMILES with the possible conformers?

**Comment by greglandrum** [comment]
This is not the place to ask RDKit questions. Please subscribe to the RDKit mailing list or try the discussions tab in the main RDKit repo
