### ISSUE TITLE
RDKit error with explicit valence for atom and Can't kekulize mol

### ISSUE THREAD

**Issue by andresilvapimentel** [greglandrum/rdkit_blog#6]
How can I solve this error? Any suggestion?

#Drawing ROMol structure
PandasTools.AddMoleculeColumnToFrame(dfoleos, smilesCol="smiles")

#Drawing ROMol structure
PandasTools.AddMoleculeColumnToFrame(dfoleos, smilesCol="smiles")
RDKit ERROR: [19:21:28] Explicit valence for atom # 0 N, 5, is greater than permitted
RDKit ERROR: [19:21:28] Can't kekulize mol.  Unkekulized atoms: 9
RDKit ERROR: 
RDKit ERROR: [19:21:28] Explicit valence for atom # 10 N, 4, is greater than permitted
RDKit ERROR: [19:21:28] Explicit valence for atom # 10 N, 4, is greater than permitted
RDKit ERROR: [19:21:28] Can't kekulize mol.  Unkekulized atoms: 4
RDKit ERROR: 
RDKit ERROR: [19:21:28] Can't kekulize mol.  Unkekulized atoms: 4
RDKit ERROR:

**Comment by greglandrum** [comment]
In order for us to help you will need to share the structures of the molecules which are failing.

**Comment by greglandrum** [comment]
Please ask RDKit questions using the rdkit github discussions: https://github.com/rdkit/rdkit/discussions

**Comment by andresilvapimentel** [comment]
Nobody answer in github discussions...


The chemical structures are:
[NH4][Pt]([NH4])(Cl)Cl

c1ccc(cc1)n2c(=O)c(c(=O)n2c3ccccc3)CCS(=O)c4ccccc4

Cc1cc2c(cc1C)N3C=N2[Co+]456(N7=C8[C@H](C(C7=CC9=N4C(=C(C1=N5[C@@]([C@@H]2N6C(=C8C)[C@@]([C@H]2CC(=O)N)(CCC(=O)NC[C@H](OP(=O)(O[C@@H]2[C@H](O[C@H]3[C@@H]2O)CO)[O-])C)C)([C@@]([C@@H]1CCC(=O)N)(C)CC(=O)N)C)C)[C@@]([C@@H]9CCC(=O)N)(C)CC(=O)N)(C)C)CCC(=O)N)O

Cc1cc2c(cc1C)N3C=N2[Co]456(N7=C8[C@H](C(C7=CC9=N4C(=C(C1=N5[C@@]([C@@H]2N6C(=C8C)[C@@]([C@H]2CC(=O)N)(CCC(=O)NC[C@H](OP(=O)(O[C@@H]2[C@H](O[C@H]3[C@@H]2O)CO)O)C)C)([C@@]([C@@H]1CCC(=O)N)(C)CC(=O)N)C)C)[C@@]([C@@H]9CCC(=O)N)(C)CC(=O)N)(C)C)CCC(=O)N)C#N

CCCCc1c(=O)n(n(c1=O)c2ccc(cc2)O)c3ccccc3

CCCCc1c(=O)n(n(c1=O)c2ccccc2)c3ccccc3

Could you help me, please?

**Comment by greglandrum** [comment]
@andresilvapimentel  It's important to remember that this is all being done by volunteers and that most of them answer questions in their free time. You may not get an answer immediately (or at all)... there's enough publicly available information about the RDKit that you can often figure out the answer to RDKit questions by doing a bit of web searching
